### PR TITLE
Handle edge cases when creating a new site and starting a server

### PR DESCRIPTION
**Pull request by mig824**
## Types of changes

- [x] Bugfix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [x] Refactor (change which changes the codebase without affecting its external behavior)
- [x] Non-breaking change (fix or feature that would causes existing functionality to work as expected)
- [ ] Breaking change (fix or feature that would cause existing functionality to __not__ work as expected)
## Purpose
To handle certain edge cases when creating a new site and starting a server
Create a method for checking if current workspace is empty
Create a method for checking if current workspace has a Gatsby site in it

### CODE REVIEW

**Review by bhayashi — APPROVED** [review]
Approved!

**Review by JoonyoungKim025 — APPROVED** [review]
I dig it

**Review by dylanrh — APPROVED** [review]
Great stuff

**Review by lucycchi — APPROVED** [review]
nice!

**Pull request merged**
